labprog2/seminarioime/config/routes.rb
Rails.application.routes.draw do

  post 'interests', to: 'interests#create'
  delete 'interests', to: 'interests#destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :groups
  resources :seminars, :except => :index

  get "/myarea/attendancelist", :to => 'area#attendance'
  get "/myarea/studentlist", :to => 'area#studentlist'
  get "/myarea/invite", :to => 'area#invite'
  get "/myarea/myseminars", :to => 'area#myseminars'

  post '/myarea/invite', to: 'area#create'

  post 'attendances', to: 'attendances#create'
  get 'attendances/new', to: 'attendances#new'
  get 'attendances/confirm/:rand_token', to: 'attendances#confirm_by_qr'

  get 'users/invite/:rand_token', to: 'invite#new', as: 'new_invite'

  post 'users/invite/:rand_token', to: 'invite#create', as: 'create_invite'

  post 'responsibilities', to: 'responsibilities#create'

  root to: "area#home"
end

labprog2/seminarioime/app/controllers/invite_controller.rb
class InviteController < ApplicationController

  def new
    @rand_string = SecureRandom.base58(60)
    @professor = Professor.find_by_token(params[:rand_token])

    @user = User.new()
    @user.email = @professor.email if @professor != nil
    @user.group_id = 1
    if @professor != nil
      if user_signed_in?
        flash[:notice] = "You must log off to register"
        redirect_to root_path and return
      end
      date_created = @professor.created_at.to_date
      date_today = Date.today.to_date
    else
      flash[:notice] = "Invite link invalid, expired or professor already registered"
      redirect_to root_path
    end
  end

  def create
    @form = params[:user]
    @link = request.base_url+"/users/invite/"+params[:rand_token]
    puts(@link)
    if @form[:nusp] == ""
      flash[:notice] = "NUSP can't be empty"
      redirect_to @link and return
    end
    if @form[:email] == ""
      flash[:notice] = "Email can't be empty"
      redirect_to @link and return
    end
    if @form[:name] == ""
      flash[:notice] = "Name can't be empty"
      redirect_to @link and return
    end
    if @form[:password] == "" || @form[:password].size <= 5
      flash[:notice] = "Password must have at least 6 characters"
      redirect_to @link and return
    end
    if @form[:password] != @form[:password_confirmation]
      flash[:notice] = "Password doesn't match"
      redirect_to @link and return
    end


    @user = User.new()
    @user.email = @form[:email]
    @user.name = @form[:name]
    @user.nusp = @form[:nusp]
    @user.usertype = true
    @user.group_id = @form[:group_id]
    @user.reset_password(@form[:password], @form[:password])

    Professor.find_by_email(@user.email).destroy!
    if @user.save!
      flash[:notice] = "Professor sucessfully registered"
      redirect_to '/'
    else
      puts @user.errors.to_yaml
    end
  end
end

labprog2/seminarioime/app/helpers/invite_helper.rb
module InviteHelper
end

labprog2/seminarioime/app/views/invite/new.html.erb
<style>
.v-space {
  margin-top: 15px;
}
</style>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Continue register</h2>

    <%= form_for( @user, :url => new_invite_path, :html => { :method => :post } ) do |f| %>


        <div class="field">
          <%= f.label :nusp %><br />
          <%= f.number_field :nusp, autofocus: true, :required => true, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name, :required => true, class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, :required => true, :readonly => true,  class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :group %>
          <%= f.collection_select :group_id, Group.all, :id, :name, { :include_blank => ""}, class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off", :required => true, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", :required => true, class: "form-control" %>
        </div>
        <div class="actions v-space">
          <%= f.submit "Complete sign up", class: "btn btn-info btn-block" %>
        </div>
    <% end %>
  </div>
</div>